### ISSUE TITLE
About Sizeof and Incbin

### ISSUE THREAD

**Issue by fjay69** [camsaul/nesasm#1]
Hello. I want to put into my project a binary file and put its size before it. So I do like this:
```
symbol1 .incbin "data.bin"

symbol2:
	.db sizeof(symbol1)
	.incbin "data.bin"
```
I have to use the file name twice, which is not convinient. Is there a way to use the file name only once?

**Comment by everyfan** [comment]
I *think* you can do

`symbol:. db symbol_end-symbol
    .incbin "data.bin"
symbol_end:`

but i haven't checked it

**Comment by fjay69** [comment]
Yes, it works. Thanks.
